
package furb.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Services", targetNamespace = "http://webservice.furb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Services {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerPlayer", targetNamespace = "http://webservice.furb/", className = "furb.webservice.RegisterPlayer")
    @ResponseWrapper(localName = "registerPlayerResponse", targetNamespace = "http://webservice.furb/", className = "furb.webservice.RegisterPlayerResponse")
    @Action(input = "http://webservice.furb/Services/registerPlayerRequest", output = "http://webservice.furb/Services/registerPlayerResponse")
    public boolean registerPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePlayerName", targetNamespace = "http://webservice.furb/", className = "furb.webservice.UpdatePlayerName")
    @ResponseWrapper(localName = "updatePlayerNameResponse", targetNamespace = "http://webservice.furb/", className = "furb.webservice.UpdatePlayerNameResponse")
    @Action(input = "http://webservice.furb/Services/updatePlayerNameRequest", output = "http://webservice.furb/Services/updatePlayerNameResponse")
    public boolean updatePlayerName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlayer", targetNamespace = "http://webservice.furb/", className = "furb.webservice.GetPlayer")
    @ResponseWrapper(localName = "getPlayerResponse", targetNamespace = "http://webservice.furb/", className = "furb.webservice.GetPlayerResponse")
    @Action(input = "http://webservice.furb/Services/getPlayerRequest", output = "http://webservice.furb/Services/getPlayerResponse")
    public String getPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
