interface calc_numerica {

    boolean checkForRegion(in int regionCode, out boolean ret);
    boolean updatePlayer(in string userName);  
    boolean getPlayerTimestamp(in string userName, out long timestamp);

};