package furb.corba;
/**
* InterfaceCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceCorba.idl
* Quarta-feira, 3 de Dezembro de 2014 00h59min40s BRST
*/

public interface InterfaceCorba extends InterfaceCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfaceCorba
