package furb.corba;
/**
* InterfaceCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceCorba.idl
* Terça-feira, 2 de Dezembro de 2014 18h58min39s BRST
*/

public interface InterfaceCorbaOperations 
{
  boolean checkForRegion (short regionCode);
  void updatePlayer (String userName);
  int getPlayerTimestamp (String userName);
} // interface InterfaceCorbaOperations
