package furb.corba;
/**
* InterfaceCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceCorba.idl
* Terça-feira, 2 de Dezembro de 2014 18h58min39s BRST
*/

public interface InterfaceCorba extends InterfaceCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfaceCorba
