package furb.corba;
/**
* InterfaceCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceCorba.idl
* Quarta-feira, 3 de Dezembro de 2014 00h59min40s BRST
*/

public interface InterfaceCorbaOperations 
{
  boolean checkForRegion (int regionCode);
  void updatePlayer (String userName);
  long getPlayerTimestamp (String userName);
} // interface InterfaceCorbaOperations
